git:
  depth: 150

language: go

sudo: required

services:
    - docker

cache:
    directories:
        - "${HOME}/google-cloud-sdk/"

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install btrfs-tools
    - sudo apt-get install libseccomp2
    - sudo apt-get install libseccomp-dev
    - sudo apt-get install socat

before_script:
    - export PATH=$HOME/gopath/bin:$PATH

jobs:
  include:
    - stage: Build
      script:
        - make install.tools
        - make .gitvalidation
        - make binaries
      go: "1.10.x"
    - stage: Test
      script:
        - make install.deps
        - make containerd
        - sudo make install-containerd
        - make test
        # Use a different port for stream server to avoid
        # conflict with the docker-containerd.
        - |
          sudo mkdir -p /etc/containerd
          sudo bash -c 'cat > /etc/containerd/config.toml <<EOF
          [plugins.cri]
            stream_server_port = "10011"
          EOF'
        - make test-integration
        - make test-cri
      after_script:
        # Abuse travis to preserve the log.
        - cat /tmp/test-integration/containerd.log
        - cat /tmp/test-cri/containerd.log
      go: "1.10.x"
